# Image with gcc-7 dev environment

FROM ubuntu:20.04

SHELL ["/bin/bash", "-xeuo", "pipefail", "-c"]

# disable auto-cleaning of the apt cache, so that docker caching works
RUN rm -f /etc/apt/apt.conf.d/docker-clean

# use docker cache for apt packages
RUN --mount=type=cache,target=/var/cache/apt \
<<EOT
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake make gcc g++	        
    rm -rf /var/lib/apt/lists/*
EOT